/**
 * types.ts
 *
 * Shared domain types used across all modules.
 * Keeping them in one place avoids circular imports.
 */

// ─── Market ──────────────────────────────────────────────────────────────────

/**
 * Normalised representation of a Polymarket binary market
 * after filtering + enrichment by the scanner.
 */
export interface Market {
  /** Gamma API market ID */
  id: string;

  /** Human-readable question text */
  question: string;

  /** Which crypto asset this market is about (e.g. "BTC") */
  asset: string;

  /** Duration string extracted from the question (e.g. "5-minute") */
  duration: string;

  /** ISO string for when the market closes */
  closesAt: string;

  /** Seconds remaining until market close at the time of scanning */
  timeRemainingSeconds: number;

  /**
   * The side to bet on — whichever outcome token is trading
   * at ≥ PRICE_RANGE_MIN (the "winning" high-confidence side).
   * "YES" or "NO" in Polymarket terms, but stored as token index 0 or 1.
   */
  winSide: "YES" | "NO";

  /** Current price of the win-side token (0–1) */
  winSidePrice: number;

  /** CLOB token ID for the YES outcome */
  yesTokenId: string;

  /** CLOB token ID for the NO outcome */
  noTokenId: string;

  /** The token ID we will actually buy (yesTokenId or noTokenId) */
  tokenIdToBuy: string;

  /** Whether this market needs negRisk flag when ordering */
  negRisk: boolean;

  /** Minimum tick size for this market (e.g. "0.01") */
  tickSize: string;
}

// ─── ActiveBet ───────────────────────────────────────────────────────────────

/**
 * Represents a bet that has been placed (or simulated) and is
 * awaiting market resolution.
 */
export interface ActiveBet {
  /** Internal bet UUID (generated by us) */
  betId: string;

  /** The market this bet is on */
  market: Market;

  /** Which slot is holding this bet */
  slotId: number;

  /** USDC amount staked */
  stakeUsd: number;

  /** Expected payout if we win (stake / price, floored to 2 dp) */
  expectedPayoutUsd: number;

  /** Polymarket order ID (undefined in shadow mode) */
  orderId?: string;

  /** ISO string of when the bet was placed */
  placedAt: string;

  /** Whether this is a shadow (simulated) bet */
  shadow: boolean;

  /** Which side we bet on */
  side: "YES" | "NO";

  /** Price at the time of the bet */
  priceAtBet: number;
}

// ─── OrderResult ─────────────────────────────────────────────────────────────

export interface OrderResult {
  success: boolean;
  orderId?: string;
  /** Average fill price (0–1) */
  avgPrice?: number;
  /** Whether the order was fully filled */
  filled?: boolean;
  rawResponse?: unknown;
  error?: string;
}

// ─── MarketResolution ────────────────────────────────────────────────────────

export type ResolutionOutcome = "YES" | "NO" | "PENDING" | "CANCELLED";

export interface MarketResolution {
  marketId: string;
  outcome: ResolutionOutcome;
  resolvedAt?: string;
}
